### ISSUE TITLE
NG: Key_Z and Key_Y switched on German keyboards

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/sdl.mod#16]
I just found out that my vanilla build reacts correct to keycodes for KEY_Z and KEY_Y (they are switched on German - and other - keyboard layouts, QWERTZ not QWERTY).
But on an NG build these two keys are switched.

**Comment by GWRon** [comment]
Seems my old reply was added to another issue as you moved this one ;-)


Did you check the "gist" I linked above? It explains the differences. Instead of "SDL_SCANCODE_*" one should use "SDLK_*" as it contains the mapped codes.

**Comment by GWRon** [comment]
or even simpler than the GIST:
https://wiki.libsdl.org/CategoryKeyboard
https://wiki.libsdl.org/SDL_Keycode

**Comment by GWRon** [comment]
Just want to confirm that it works now as expected.

**Comment by woollybah** [comment]
Thanks :-)
