### ISSUE TITLE
TEvent for Mouse clicks ignores 4th and 5th button

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/sdl.mod#24]
Clicks on the 4th or 5th mousebutton lead to the TEvent.data contain "0" or "1" (so 0th button or primary mouse button). System: Windows 10 with a 5 button mouse.

Related to bmx-ng/brl.mod#159

Albeit here "sdlsystem.mod/glue.c" seems to take care of buttons 1-5

**Comment by woollybah** [comment]
Should be fixed.
