### ISSUE TITLE
D3D9SDLMax2DDriver error with null object

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/sdl.mod#3]
Title says it all really. Currently trying to use the 'unknownPtr' of a null instance of a IDirect3DBaseTexture9.
Can be fixed by changing a couple of lines.
In file 'd3d9sdlmax2d.bmx' change lines 74 and 344 to

    _d3dDev.SetTexture 0,New IDirect3DBaseTexture9

As the methods that contain these changes are only really used during an initialising or destroying phase of resource management then creating new empty IDirect3DBaseTexture9 instances shouldn't pose any speed concerns.

**Comment by GWRon** [comment]
Would it be possible to have a `nullBaseTexture` which could be used for such things? Dunno if that object might get exposed somewhere..if so, your "fire and forget" approach will be a better variant. I do not have "comfortable" access to the code now ... so excuse the question: if this is called on create and desttoy of a context..isn't it using different objects then (have no clue what is done to the texture object)? So memory might get leaked.


Think Brucey will be happy to get someone doing the graphics stuff (remembering the shader-bug-hunt).

Good that your projects are tackling other parts of the NG project...exposing more and more of these little issues lurking around in the darkest corner of our ".bmx"-folders.

**Comment by davecamp** [comment]
Those 2 calls are originally designed to set the low level d3ddevice 'current texture' to a null texture via a null pointer ( remembering that gpus are state machines ) so that it can reset the device properly. Because those calls are actually wrapper calls they should have a valid instance of a IDirect3DBaseTexture9 object which will have its underlying .unknownPtr ( the real gpu texture pointer ) set to null as opposed to passing a Null object instance. The only thing going through my mind was creating a new object instance and the speed involved. It shouldn't matter as one is called during a device reset ( maybe a 'live' screen resolution change ), and the other when a texture goes out of scope, has it real texture pointer freed and so therefore needs to set the real d3ddevice 'current texture' to null so as not to use an invalid low level texture pointer.

I did originally try a single global instance called 'D3D9NullTexture' in the same file but then there are only 2 instances ( that I could see ) where it's used so I thought it to be a little unnecessary. Maybe if there were more required instances of a null texture... but then thinking about it as I'm typing, using a 'nullBaseTexture' style variable name is given a clear intention that the call is intending to set the texture to null. So I actually think that idea is better - on the basis of its intention.

ref projects:-
I'm doing some HEAVY multithreading in bmax so it's fair to say that I'm probably pushing the language and its underlying runtime core :-)
I even have fibers working in bmax but the original and boehm garbage collectors really aren't happy with using them, so they are a definite no-no for the time being.

Glad to be on-board to hopefully help out.
