### ISSUE TITLE
Raspberry Pi - Transparent parts of images are drawn black

### ISSUE THREAD

**Issue by fightlessbirds** [bmx-ng/sdl.mod#30]
On the [current release](https://github.com/bmx-ng/bmx-ng/releases/tag/v0.129.3.45.rpi.arm) of BlitzMax for Raspberry Pi running the sample birdie/lightImage will fail to draw the transparent parts of the BMax logo. Instead it will have a black square background.

Relevant discussion on the bug: [https://bugzilla.libsdl.org/show_bug.cgi?id=4365#c112](https://bugzilla.libsdl.org/show_bug.cgi?id=4365#c112)

I've testing this on RPi 2 and RPi 400.

**Comment by woollybah** [comment]
The `MASKBLEND` blend mode isn't supported by OpenGLES - or more precisely, `glBlendFunc()` isn't - so setting it wouldn't do anything - this was the mode used in the lightimage sample for the logo.

I've now implemented something that attempts to replicate the blend mode as part of the default fragment shader, which appears to work for the sample at least.
