### ISSUE TITLE
Update SDL to support OpenURL

### ISSUE THREAD

**Issue by ChaosCoder** [bmx-ng/sdl.mod#31]
Currently, the sdl.mod does not support the OpenURL method (as seen here with a TODO-comment):
https://github.com/bmx-ng/sdl.mod/blob/59ef1173eb026e075c3412fecd7c80ba4f74cdae/sdlsystem.mod/sdlsystem.bmx#L174-L176

Version 2.0.14 of SDL released on 21 Dec 2020 supports the `SDL_OpenURL()` command.

By updating the current SDL version 2.0.13 to 2.0.14 we should be able to implement the function to allow opening of links in the user's browser.

I tried it myself with my limited knowledge of the while SDL setup, as I needed that function for a project of mine, but unfortunately I didn't succeed and got stuck with linker errors. It would be great, if someone could try it.

**Comment by woollybah** [comment]
I've updated to the latest libSDL. Can you check if it is working for you now?

**Comment by ChaosCoder** [comment]
Thank you so much! I had to fix just a couple of lines to include stuff needed on macOS. See #32 
I will close this issue now.
