### ISSUE TITLE
Identifier 'GRAPHICS_WIN32_DX' not found in the latest commit

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/sdl.mod#38]
Hiya,
From a clean NG repo download:

```
Building Modules
[ 15%] Processing:d3d9sdlgraphics.bmx
[ 15%] Processing:glsdlgraphics.bmx
Compile Error: Identifier 'GRAPHICS_WIN32_DX' not found.
```

fails at
`mod/sdl.mod/d3d9sdlgraphics.mod/d3d9sdlgraphics.bmx;167;0]`

**Comment by GWRon** [comment]
hmm just built latest sdl.mod with latest brl, pub, bcc, bmk ... did not fail here
