### ISSUE TITLE
Expose "SDL_Log()"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/sdl.mod#4]
Currently I do not see an option to write something to the android log.

SDL provides "SDL_Log()" for this:
https://wiki.libsdl.org/SDL_Log

But I do not see it exposed for use in BMX-NG. Adding this, would provide easier ways to provide some kind of "debug information" (via `adb logcat | grep blitzmax` ;-)).

**Comment by woollybah** [comment]
Added a bunch of logging functions.
