### ISSUE TITLE
(SDL) GetBasePath() returns Null - "not compiled with sdl 2.0"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/sdl.mod#5]
When using "GetBasePath()" on my android device I get the following `SDL_GetError()`-message:
`Application not compiled with SDL 2.0`

The result is, that GetBasePath() returns an empty string (as `SDL_GetBasePath()` returns null)

**Comment by GWRon** [comment]
Having a look at sdl.mod/SDL/src/filesystem/android/SDL_filesystem.c, `GetBasePath()" can only return Null ...  so it seems to do what it should.

**Comment by woollybah** [comment]
You may want AndroidGetInternalStoragePath() instead?

**Comment by GWRon** [comment]
Nope, I wanted to make "libxml" be able to load a file from the assets-folder ... so I wanted to get the absolute path to the file on the android device.

**Comment by GWRon** [comment]
Assume this is not possible as SDL directly loads from the APK. And as long as libXML does try to load it on its own, it wont do.

So I could try to circumvent it by loading the content via SDL and then feeding libXML with the string rather than the file.

**Comment by woollybah** [comment]
Can't you load via a TStream and ReadDoc() ?

**Comment by GWRon** [comment]
This is exactly what I tried to explain in the "circumvent"-phrase. Just having a google-look if there is an alternative. For now this is not that problematic, but if you imagine to have passed a bigger XML file (some MB) this means to have it completely stored in RAM when loading.

**Comment by woollybah** [comment]
How so? If you are reading from a TStream you are reading it directly from some file.

**Comment by GWRon** [comment]
Yeah but I have to load it to a string first (s:string = ReadStream("sdl::myxml.xml"). Then I can pass this string to libXML's parseDoc.

Or did I misunderstood something?

**Comment by woollybah** [comment]
* Parse an XML document from a String or TStream and build a tree.
```Function ReadDoc:TxmlDoc(doc:Object...)```

ReadDoc accepts a TStream, and *should* be able to load a TxmlDoc from it.

**Comment by GWRon** [comment]
Will give it a try  .. totally missed that part.

**Comment by GWRon** [comment]
Short question: When using `ReadDoc()` with an `OpenStream()`-stream: when to close the stream? is after calling `ReadDoc()` enough?

**Comment by woollybah** [comment]
Yes, it should have finished loading it when the function returns.

**Comment by GWRon** [comment]
Ok, Thanks ... having some crashes now, it is time to check your new SDL_Log()-functions

**Comment by GWRon** [comment]
... Ok, loads the XML now on android. Thanks to SDL_Log() - and your help  ;-)

**Comment by woollybah** [comment]
Cool :-)
