### ISSUE TITLE
Some errors about functions (Byte redefinition)

### ISSUE THREAD

**Issue by eagle54** [bmx-ng/sdl.mod#9]
see https://github.com/bmx-ng/bcc/issues/214
see https://github.com/bmx-ng/maxgui.mod/issues/6

It's not possible to build sdl mod without Byte redefinition, see :

`glVertexAttribPointer( attrib_pos, 2, GL_FLOAT, GL_FALSE, 0, vert_array ) -> glVertexAttribPointer( attrib_pos, 2, GL_FLOAT, Byte(GL_FALSE), 0, vert_array )`

**Comment by woollybah** [comment]
Fixed.
